# Generated by Django 2.2.5 on 2020-05-24 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_is_available', models.BooleanField(blank=True, default=False, null=True, verbose_name='活动是否结束')),
                ('act_need_audit', models.BooleanField(blank=True, default=False, null=True, verbose_name='是否需要审核')),
                ('act_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='活动标题')),
                ('act_date', models.DateField(blank=True, null=True, verbose_name='活动时间')),
                ('act_loc', models.CharField(blank=True, max_length=128, null=True, verbose_name='活动地点')),
                ('act_method', models.CharField(blank=True, max_length=128, null=True, verbose_name='活动方式')),
                ('act_description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='活动描述')),
            ],
            options={
                'verbose_name': '活动管理',
                'verbose_name_plural': '活动管理',
            },
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='活动标题')),
                ('diary_date', models.DateField(blank=True, null=True, verbose_name='活动时间')),
                ('diary_loc', models.CharField(blank=True, max_length=128, null=True, verbose_name='活动地点')),
                ('diary_method', models.CharField(blank=True, max_length=128, null=True, verbose_name='活动方式')),
                ('diary_exp', models.TextField(blank=True, null=True, verbose_name='活动感悟')),
                ('diary_advice', models.TextField(blank=True, max_length=128, null=True, verbose_name='活动建议')),
                ('related_act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.Activity', verbose_name='关联活动')),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '活动足迹',
                'verbose_name_plural': '活动足迹',
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_status', models.CharField(choices=[('0', '申请未处理'), ('1', '申请通过'), ('2', '申请拒绝')], default='0', max_length=128, verbose_name='申请结果')),
                ('audit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请人账号')),
                ('relate_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.Activity', verbose_name='关联活动')),
            ],
            options={
                'verbose_name': '活动参加申请管理',
                'verbose_name_plural': '活动参加申请管理',
            },
        ),
    ]
