# Generated by Django 2.2.5 on 2020-05-30 07:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='audit_status',
            field=models.CharField(choices=[('4000', '申请未处理'), ('4001', '申请通过'), ('4002', '申请拒绝')], default='4000', max_length=128, verbose_name='申请结果'),
        ),
        migrations.AlterUniqueTogether(
            name='audit',
            unique_together={('audit_user', 'relate_activity')},
        ),
    ]
