# Generated by Django 2.2.5 on 2020-05-24 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='活动标题')),
                ('diary_date', models.DateField(blank=True, null=True, verbose_name='活动时间')),
                ('diary_loc', models.CharField(blank=True, max_length=128, null=True, verbose_name='活动地点')),
                ('diary_method', models.CharField(blank=True, max_length=128, null=True, verbose_name='活动方式')),
                ('diary_exp', models.TextField(blank=True, null=True, verbose_name='活动感悟')),
                ('diary_advice', models.TextField(blank=True, max_length=128, null=True, verbose_name='活动建议')),
                ('related_act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.Activity', verbose_name='关联活动')),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
        ),
    ]
