# Generated by Django 2.2.5 on 2020-05-24 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20200524_1835'),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='audit_member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='membership.MbrCommon'),
            preserve_default=False,
        ),
    ]
