# Generated by Django 2.2.5 on 2020-08-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20200530_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='audit_status',
            field=models.CharField(choices=[('4000', '申请未处理'), ('4001', '申请通过'), ('4002', '申请拒绝')], default='4002', max_length=128, verbose_name='申请结果'),
        ),
    ]
