# Generated by Django 2.2.5 on 2020-05-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_audit_audit_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='audit_member',
        ),
    ]
