# Generated by Django 2.2.5 on 2020-05-28 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0003_mbrcommon_mbr_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncCert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QRCode', models.ImageField(blank=True, null=True, upload_to='QRCodes/inc/')),
                ('cert_code', models.CharField(blank=True, max_length=128, null=True, verbose_name='证书编号')),
                ('mbr_code', models.DateField(blank=True, null=True, verbose_name='会员编号')),
                ('exp', models.DateField(blank=True, null=True, verbose_name='有效期')),
            ],
            options={
                'verbose_name': '单位证书',
                'verbose_name_plural': '单位证书',
            },
        ),
        migrations.CreateModel(
            name='MbrCert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QRCode', models.ImageField(blank=True, null=True, upload_to='QRCodes/inc/')),
                ('cert_type', models.CharField(blank=True, max_length=128, null=True, verbose_name='证书类型')),
                ('relate_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.MbrCommon', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '个人证书',
                'verbose_name_plural': '个人证书',
            },
        ),
    ]
