# Generated by Django 2.2.5 on 2020-05-23 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbrinc',
            name='mbse_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
        migrations.AddField(
            model_name='mbrcommon',
            name='mbse_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
        migrations.CreateModel(
            name='CommonAudit',
            fields=[
            ],
            options={
                'verbose_name': '待审核普通会员',
                'verbose_name_plural': '待审核普通会员',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('membership.mbrcommon',),
        ),
        migrations.CreateModel(
            name='CommonFormal',
            fields=[
            ],
            options={
                'verbose_name': '普通会员',
                'verbose_name_plural': '普通会员',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('membership.mbrcommon',),
        ),
        migrations.CreateModel(
            name='IncAudit',
            fields=[
            ],
            options={
                'verbose_name': '待审核理事单位',
                'verbose_name_plural': '待审核理事单位',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('membership.mbrinc',),
        ),
        migrations.CreateModel(
            name='IncFromal',
            fields=[
            ],
            options={
                'verbose_name': '理事单位会员',
                'verbose_name_plural': '理事单位会员',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('membership.mbrinc',),
        ),
        migrations.CreateModel(
            name='IncUnactived',
            fields=[
            ],
            options={
                'verbose_name': '未激活机构',
                'verbose_name_plural': '未激活机构',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('membership.mbrinc',),
        ),
        migrations.CreateModel(
            name='MbrUnactived',
            fields=[
            ],
            options={
                'verbose_name': '未激活用户',
                'verbose_name_plural': '未激活用户',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('membership.mbrcommon',),
        ),
        migrations.CreateModel(
            name='SeniorAudit',
            fields=[
            ],
            options={
                'verbose_name': '待审核高级会员',
                'verbose_name_plural': '待审核高级会员',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('membership.mbrcommon',),
        ),
        migrations.CreateModel(
            name='SeniorFormal',
            fields=[
            ],
            options={
                'verbose_name': '高级会员',
                'verbose_name_plural': '高级会员',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('membership.mbrcommon',),
        ),
    ]
