# Generated by Django 2.2.5 on 2020-05-24 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20200523_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbrcommon',
            name='mbse_type',
        ),
        migrations.RemoveField(
            model_name='mbrinc',
            name='mbse_type',
        ),
    ]
