# Generated by Django 2.2.5 on 2020-05-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20200527_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbrcommon',
            name='mbr_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='照片'),
        ),
    ]
