# Generated by Django 2.2.5 on 2020-05-30 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_mbrcommon_mbr_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbrcommon',
            name='mbse_status',
            field=models.CharField(choices=[('2000', '已注册，未提交申请'), ('2001', '申请审核中'), ('2002', '申请驳回，请检查申请信息'), ('2003', '审核通过，等待缴费'), ('2004', '缴费校验中'), ('2005', '缴费校验不通过，请重新确认'), ('2006', '已成为正式会员')], default='2001', max_length=128, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='mbrcommon',
            name='mbse_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
        migrations.AlterField(
            model_name='mbrinc',
            name='mbse_status',
            field=models.CharField(choices=[('2000', '已注册，未提交申请'), ('2001', '申请审核中'), ('2002', '申请驳回，请检查申请信息'), ('2003', '审核通过，等待缴费'), ('2004', '缴费校验中'), ('2005', '缴费校验不通过，请重新确认'), ('2006', '已成为正式会员')], default='2001', max_length=128, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='mbrinc',
            name='mbse_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
    ]
