# Generated by Django 2.2.5 on 2020-05-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_auto_20200524_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mbrcommon',
            old_name='mbr_name',
            new_name='mbse_name',
        ),
        migrations.RemoveField(
            model_name='mbrinc',
            name='inc_name',
        ),
        migrations.AddField(
            model_name='mbrinc',
            name='mbse_name',
            field=models.CharField(blank=True, default='空', max_length=128, null=True, verbose_name='姓名'),
        ),
    ]
