# Generated by Django 2.2.5 on 2020-08-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_auto_20200530_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbrcommon',
            name='mbr_edu',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='学历'),
        ),
    ]
