# Generated by Django 2.2.5 on 2020-10-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_mbrcommon_mbr_edu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbrcommon',
            name='mbr_graduate',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='专业'),
        ),
    ]
