# Generated by Django 2.2.5 on 2020-05-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(blank=True, max_length=128, null=True, verbose_name='订单号')),
                ('price', models.CharField(blank=True, max_length=128, null=True, verbose_name='应缴金额')),
                ('method', models.CharField(blank=True, max_length=128, null=True, verbose_name='缴费方式')),
                ('exp', models.CharField(blank=True, max_length=128, null=True, verbose_name='会员有效期')),
                ('date', models.CharField(blank=True, max_length=128, null=True, verbose_name='订单形成时间')),
                ('status', models.CharField(blank=True, max_length=128, null=True, verbose_name='订单状态')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
            },
        ),
    ]
