# Generated by Django 2.2.5 on 2020-05-27 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0002_orderinc_relate_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinc',
            name='relate_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
        migrations.AddField(
            model_name='order',
            name='relate_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.MbrCommon', verbose_name='关联会员'),
        ),
        migrations.AddField(
            model_name='order',
            name='relate_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
    ]
