# Generated by Django 2.2.5 on 2020-05-25 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20200524_1835'),
        ('financial', '0002_order_ouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='relate_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.MbrCommon', verbose_name='关联会员'),
        ),
    ]
