# Generated by Django 2.2.5 on 2020-05-25 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_order_relate_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ouser',
        ),
    ]
