# Generated by Django 2.2.5 on 2020-05-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_auto_20200527_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('3000', '未缴费'), ('3001', '用户缴费，等待审核'), ('3002', '审核不通过'), ('3003', '审核通过')], default='3000', max_length=128, verbose_name='订单状态'),
        ),
    ]
