# Generated by Django 2.2.5 on 2020-05-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='identity',
            field=models.CharField(choices=[('0', '未激活'), ('1001', '普通会员'), ('1002', '高级会员'), ('1003', '理事会员')], default='0', max_length=16, verbose_name='用户类型'),
        ),
    ]
