# Generated by Django 2.2.5 on 2020-05-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='identity',
            field=models.CharField(choices=[('0', '未激活'), ('1', '普通会员'), ('2', '高级会员'), ('3', '理事会员')], default='0', max_length=16, verbose_name='用户类型'),
        ),
    ]
